# Upstream resolvers
no-resolv
server=1.1.1.1
server=1.0.0.1

# Basic hardening
domain-needed
bogus-priv
no-hosts
cache-size=10000
neg-ttl=60

# Listen only inside VPN tunnel interface/address
interface=awg0
listen-address=10.80.0.1
bind-dynamic

# Load domain block rules
conf-dir=/etc/dnsmasq.d/lists,*.conf
